# Generated by Django 3.1.2 on 2020-10-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0002_menu_school_schooldistrict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='item',
            new_name='name',
        ),
    ]
