# Generated by Django 3.1.2 on 2020-11-19 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lapp.school')),
            ],
        ),
    ]
