# Generated by Django 3.1.2 on 2020-11-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lapp', '0002_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='prep',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
